### ISSUE TITLE
Implement function to execute tests

### ISSUE THREAD

**Issue by EliasStihl** [DD2480-group-30/CI-server#6] opened 2024-02-06 11:45 UTC
The CI server supports executing the automated tests of the group project. Testing is triggered as webhook, on the branch where the change has been made, as specified in the HTTP payload.

**Comment by karindev** [comment] 2024-02-14 12:00
Was a duplicate of build as build and test are run simultaneously.

**Closed** 2024-02-14 12:00 UTC
Labels: enhancement
